## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("FlightMechanics"); Pkg.test("FlightMechanics"; coverage=true)'
after_success:
  # push coverage results to Coverall
  - julia -e 'using Pkg; cd(Pkg.dir("FlightMechanics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("FlightMechanics")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # Documenter  
  - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps)'
  - julia -e 'using Pkg; ENV["DOCUMENTER_DEBUG"] = "true"; cd(Pkg.dir("FlightMechanics")); include(joinpath("docs", "make.jl"))'
