site_name:        FlightMechanics.jl
repo_url:         https://github.com/AlexS12/FlightMechanics.jl
site_description: Flight Mechanics Utils
site_author:      Alex Saez

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - API Reference: api-reference.md
  - Basics:
    - isa.md
    - coordinate-systems.md
    - dynamic_models.md
    - anemometry.md
    - kinematics.md
